"""add events table

Revision ID: 4b44c691b769
Revises: f8a1b2c3d4e5
Create Date: 2026-06-13 04:26:31.796715

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4b44c691b769'
down_revision = 'f8a1b2c3d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        'received_at', sa.DateTime(timezone=True),
        server_default=sa.text('now()'), nullable=False,
    ),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_events_device_id'), ['device_id'], unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_events_received_at'), ['received_at'], unique=False,
        )
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_received_at'))
        batch_op.drop_index(batch_op.f('ix_events_device_id'))

    op.drop_table('events')
    # ### end Alembic commands ###
